Repository hellohaptik/docs_haptik, pull requests merged in 2019-09, with the labels that each got.

#178 update documentation for pinned chat webhook
  docs/webhooks/webhook-payload.md
Labels: documentation update

#184 update title of whatsapp language settings
  docs/whatsapp/whatsapp-language-settings.md
Labels: bug

#185 Update sending notifications WA documentation
  docs/whatsapp/sending-notifications.md
Labels: enhancement

#180 Update documentation for custom variables
  docs/bot-builder/advanced/integrating-custom-code.md
  website/i18n/en.json
Labels: documentation update

#186 Update webhook payload docs with the new keys that will be sent
  docs/webhooks/webhook-payload.md
Labels: enhancement
