Repository hellohaptik/docs_haptik, pull requests merged in 2019-10, with the labels that each got.

#191 Remove unused files from docs
  docs/agent-chat/admin_panel.md
  docs/agent-chat/assets/all_custom_tools.png
  docs/agent-chat/assets/athena_LHS.png
  docs/agent-chat/assets/athena_admin_panel.png
  docs/agent-chat/assets/athena_location.png
  docs/agent-chat/assets/athena_panel.png
  docs/agent-chat/assets/athena_rhs.png
  docs/agent-chat/assets/reminders_custom_tool.png
  docs/agent-chat/athena_lhs.md
  docs/agent-chat/athena_rhs.md
  docs/agent-chat/custom-tools-data-communication.md
  docs/agent-chat/custom-tools-intro.md
Labels: enhancement

#190 Pass env variables in payload for external integration
  docs/bot-builder/integrations/integrating-apis.md
Labels: documentation update

#188 pass chat link
  docs/webhooks/webhook-payload.md
Labels: documentation update

#196 [docs][athena] update athena sdk integration
  docs/agent-chat/adding-custom-tools.md
Labels: documentation update

#195 Fix broken links of user journey
  docs/bot-analytics/assets/node-traffic-node-detailed-view.png
  docs/bot-analytics/assets/node-traffic-node-list.png
  docs/bot-analytics/assets/user-journey-node-traversal-graph.png
  docs/bot-analytics/node-traffic.md
  docs/bot-analytics/sample-metrics.md
Labels: bug

#192 Update Technical docs for WhatsApp
  docs/whatsapp/technical-setup.md
Labels: documentation update

#198 [docs][Athena] chat disposition for custom tools
  docs/agent-chat/adding-custom-tools.md
Labels: documentation update

#199 [docs][athena] sdk version update
  docs/agent-chat/adding-custom-tools.md
Labels: documentation update

#197 Update docs with the new params that are supported in Webhook signup
  docs/webhooks/create-haptik-user.md
  docs/webhooks/webhook-payload.md
Labels: enhancement

#203 [athena] business settings
  docs/agent-chat/assets/business_settings.png
  docs/agent-chat/claiming-and-closing.md
Labels: documentation update
