Repository hellohaptik/docs_haptik, pull requests merged in 2019-03, with the labels that each got.

#78 Fix the agent-chat meta file syntax
  docs/agent-chat/meta.json
Labels: bug

#94 fix typos
  docs/bot-builder/advanced/integrating-custom-code.md
Labels: documentation update

#98 Add hsl example in bot response
  docs/bot-builder/advanced/integrating-custom-code.md
  docs/bot-builder/assets/advanced-ui-element.png
Labels: documentation update

#99 upload screenshot of hsl example
  docs/bot-builder/assets/advanced-ui-element.png
Labels: documentation update

#106 Fix indentation in sample code
  docs/bot-builder/advanced/integrating-custom-code.md
Labels: bug

#120 will remove typos and improve the formatting
  docs/webhooks/api-security-rules.md
  docs/webhooks/create-haptik-user.md
  docs/webhooks/index.md
  docs/webhooks/protocols.md
  docs/webhooks/re-enable-webhook.md
  docs/webhooks/rules-webhook-creation.md
  docs/webhooks/send-image-to-haptik.md
  docs/webhooks/send-message-to-haptik.md
  docs/webhooks/webhook-payload.md
Labels: documentation update

#124 Update documentation for message analysis changes
  docs/bot-analytics/assets/message-analysis-download.png
  docs/bot-analytics/assets/message-analysis/message-analysis-download.png
  docs/bot-analytics/assets/message-analysis/message-analysis-exact-search.gif
  docs/bot-analytics/assets/message-analysis/message-analysis-search-body.png
  docs/bot-analytics/using-message-analysis.md
Labels: enhancement
