Repository hellohaptik/docs_haptik, pull requests merged in 2020-05, with the labels that each got.

#269 Documentation for HSM buttons
  docs/whatsapp/assets/hsm_buttons/call-to-action-button.png
  docs/whatsapp/assets/hsm_buttons/quick-replies.png
  docs/whatsapp/assets/hsm_buttons/whatsapp_call-to-action.jpg
  docs/whatsapp/assets/hsm_buttons/whatsapp_quick-replies.jpg
  docs/whatsapp/sending-notifications.md
Labels: enhancement

#270 Reolving bugs associated with the markdown syntax
  docs/whatsapp/sending-notifications.md
Labels: bug

#271 Add documentation for TimeZone permission
  docs/other/assets/FB-APP-LEVEL-PERMISSION.jpeg
  docs/other/assets/FB-PAGE-LEVEL-PERMISSIONS.jpeg
  docs/other/facebook.md
Labels: documentation update
