Repository hellohaptik/docs_haptik, pull requests merged in 2020-07, with the labels that each got.

#291 Agent Reports documentation
  docs/agent-chat/agent-reports.md
  docs/agent-chat/meta.json
Labels: documentation update

#299 iOS documentation migration
  docs/ios-sdk/analytics.md
  docs/ios-sdk/assets/Clevertap_credentials.png
  docs/ios-sdk/assets/Main_Credentials_plist.png
  docs/ios-sdk/assets/Prod_Credentials_Plist.png
  docs/ios-sdk/assets/Share_And_Rate.png
  docs/ios-sdk/assets/lfs_buil_error.png
  docs/ios-sdk/conversations.md
  docs/ios-sdk/faq.md
  docs/ios-sdk/features.md
  docs/ios-sdk/index.md
  docs/ios-sdk/location.md
  docs/ios-sdk/meta.json
  docs/ios-sdk/notifications.md
  docs/ios-sdk/permissions.md
  docs/ios-sdk/rate-share.md
  docs/ios-sdk/sdk-sample.md
  docs/ios-sdk/sign-up.md
  docs/ios-sdk/theming.md
  docs/ios-sdk/voice.md
  website/pages/en/index.js
  website/static/js/index.js
Labels: documentation update

#300 TRACT | Minor API spec update
  docs/external-chat-tool/message-APIs.md
Labels: bug

#298 Android documentation migration
  docs/android-sdk/additional-features.md
  docs/android-sdk/assets/inbox-view.png
  docs/android-sdk/assets/messaging-screen.png
  docs/android-sdk/assets/signup-flow.png
  docs/android-sdk/configure-advanced-functionality.md
  docs/android-sdk/configuring-push-notifications.md
  docs/android-sdk/core-module-integration.md
  docs/android-sdk/extension-module-integration.md
  docs/android-sdk/faqs.md
  docs/android-sdk/image-loading-modules.md
  docs/android-sdk/index.md
  docs/android-sdk/integrating-jio-communications-module.md
  docs/android-sdk/language-support.md
  docs/android-sdk/launch-chat-activity.md
  docs/android-sdk/meta.json
  docs/android-sdk/migrating-from-earlier-versions.md
  docs/android-sdk/multiple-clevertap-account-issue.md
  docs/android-sdk/offerings.md
  docs/android-sdk/overview.md
  docs/android-sdk/permissions.md
  docs/android-sdk/rate-share.md
  docs/android-sdk/sdk-sample.md
  docs/android-sdk/sign-up.md
  docs/android-sdk/style-guide.md
  docs/android-sdk/voice-support.md
  docs/android-sdk/xdk-module-integration.md
  website/core/Footer.js
  website/pages/en/index.js
  website/static/js/index.js
Labels: documentation update

#306 Updated docs with new Android SDK
  docs/android-sdk/extension-module-integration.md
  docs/android-sdk/image-loading-modules.md
  docs/android-sdk/index.md
  docs/android-sdk/integrating-jio-communications-module.md
  docs/android-sdk/migrating-from-earlier-versions.md
  docs/android-sdk/xdk-module-integration.md
Labels: documentation update

#307 SDK version updated
  docs/ios-sdk/index.md
Labels: documentation update

#309 Update the documentation for latest Android SDK release
  docs/android-sdk/extension-module-integration.md
  docs/android-sdk/image-loading-modules.md
  docs/android-sdk/index.md
  docs/android-sdk/integrating-jio-communications-module.md
  docs/android-sdk/migrating-from-earlier-versions.md
  docs/android-sdk/xdk-module-integration.md
Labels: documentation update

#312 New bot prompts documentation
  docs/bot-builder/assets/new_bot_prompts/new-prompt.png
  docs/bot-builder/assets/new_bot_prompts/prompt-rules.png
  docs/bot-builder/assets/new_bot_prompts/prompt-variations.png
  docs/bot-builder/basic/bot-prompt-trigger.md
Labels: enhancement

#315 Update the documentation for latest Android SDK release
  docs/android-sdk/extension-module-integration.md
  docs/android-sdk/image-loading-modules.md
  docs/android-sdk/index.md
  docs/android-sdk/integrating-jio-communications-module.md
  docs/android-sdk/migrating-from-earlier-versions.md
  docs/android-sdk/xdk-module-integration.md
Labels: documentation update

#304 Update webhooks documentation to include document upload
  .gitignore
  docs/webhooks/create-haptik-user.md
  docs/webhooks/meta.json
  docs/webhooks/send-file-to-haptik.md
  docs/webhooks/send-message-to-haptik.md
  docs/webhooks/using-platform-deployments.md
  website/i18n/en.json
Labels: documentation update
